[package]
name = "forezy_contracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.4"
openzeppelin = "2.0.0"

[dev-dependencies]
cairo_test = "2.11.4"

[[target.starknet-contract]]
casm = true